from app.services.bpp_purchasing import BPP_PERMISSION_DEFINITIONS
from app.services.independent_purchasing import INDEPENDENT_PERMISSION_DEFINITIONS
from app.services.notification_defaults import GLOBAL_NOTIFICATION_PERMISSION_DEFINITIONS

CORE_PERMISSION_DEFINITIONS: dict[str, str] = {
    "system.admin": "Full system administration access.",
    "system.health.read": "Read protected system health and operational diagnostics.",
    "roles.manage": "Manage custom roles and their permission assignments.",
    "configuration.manage": "Manage BTSP configuration entries.",
    "stores.manage": "Manage store authority records.",
    "stores.read": "Read store authority records.",
    "snapshots.read": "Read snapshot audit records.",
    "audit.export": "Export filtered immutable audit records.",
    "workflows.read": "Read available workflow routing.",
    "workflows.manage": "Inspect and activate versioned workflow definitions.",
    "orders.bpp.manage": "Manage BPP ordering workflow.",
    "orders.independent.manage": "Manage Independent ordering workflow.",
    "vendor.integrations.manage": "Manage vendor integration endpoints.",
    "vendor.integrations.read": "Read vendor integration endpoints and inbound events.",
    "vendor.integrations.ingest": "Record authenticated inbound vendor events.",
    "vendor.acknowledgements.process": "Process inbound vendor PO acknowledgements.",
    "vendor.logistics.process": "Process inbound vendor shipment updates and ASNs.",
    "vendor.connectors.operate": "Manage connector schedules, retries, and dead letters.",
    "vendor.connectors.work": "Claim and complete connector execution jobs.",
    "receiving.read": "Read purchase receipts within assigned store authority.",
    "receiving.manage": "Post purchase receipts within assigned store authority.",
    "receiving.variances.manage": "Resolve or waive receipt variances within store authority.",
    "receiving.backorders.manage": "Create and resolve backorders within store authority.",
    "invoices.read": "Read vendor invoices and deterministic line matches.",
    "invoices.manage": "Ingest vendor invoices for purchase-order matching.",
    "reconciliation.read": "Read invoice reconciliation cases and exceptions.",
    "reconciliation.manage": "Resolve reconciliation exceptions and record final decisions.",
    "analytics.read": "Read operational purchasing and reconciliation analytics.",
    "analytics.reports.manage": "Manage and generate scheduled analytics reports.",
    "communications.read": "Read internal BTSP messages and recipient directory.",
    "communications.send": "Send internal messages to active BTSP users.",
    "events.read": "Read assigned purchasing event schedules and maps.",
    "events.manage": "Create and manage purchasing events, schedules, and maps.",
    "vendor_hall.read": "Read vendor hall booth inventory and setup status.",
    "vendor_hall.manage": "Manage vendor hall setup configuration and booth oversight.",
    "vendor_hall.vendor.manage": "Manage assigned vendor hall booth inventory.",
    "vendor_hall.staff.checkin": "Perform vendor hall booth inventory check-in.",
    "vendor_hall.export": "Export vendor hall inventory, exception, and activity reports.",
    "vendor_hall.map.manage": "Manage vendor hall floor maps and booth layout.",
    "store_loadout.read": "Read store loadout assignments and progress.",
    "store_loadout.manage": "Manage store loadout assignment and oversight.",
    "store_loadout.store.checkin": "Perform assigned store loadout item check-in.",
    "store_loadout.schedule.manage": "Manage store loadout departure scheduling.",
    "store_loadout.export": "Export store loadout packing lists and reports.",
    "event_settlement.read": "Read event settlement, loadout closeout, and reconciliation packets.",
    "event_settlement.manage": "Manage event settlement exceptions and closeout decisions.",
    "event_settlement.export": "Export event settlement packets and reconciliation evidence.",
    "vendor.portal": "Access vendor-identity-scoped purchasing tools.",
    "catalog.models.read": "Search model details and cost history without modification rights.",
    "purchase_orders.handoff": "Mark delivered purchase orders ready for reconciliation custody.",
    **BPP_PERMISSION_DEFINITIONS,
    **GLOBAL_NOTIFICATION_PERMISSION_DEFINITIONS,
    **INDEPENDENT_PERMISSION_DEFINITIONS,
}

CORE_ROLE_DEFINITIONS: dict[str, dict[str, object]] = {
    "SYSTEM_ADMIN": {
        "name": "System Administrator",
        "workflow_code": None,
        "permissions": list(CORE_PERMISSION_DEFINITIONS.keys()),
    },
    "BPP_ADMIN": {
        "name": "BPP Administrator",
        "workflow_code": "BPP",
        "permissions": [
            "workflows.read",
            "orders.bpp.manage",
            "snapshots.read",
            "notifications.read",
            "notifications.send",
            "communications.read",
            "communications.send",
            *BPP_PERMISSION_DEFINITIONS.keys(),
        ],
    },
    "INDEPENDENT_ADMIN": {
        "name": "Independent Administrator",
        "workflow_code": "INDEPENDENT",
        "permissions": [
            "workflows.read",
            "orders.independent.manage",
            "snapshots.read",
            "notifications.read",
            "notifications.send",
            "communications.read",
            "communications.send",
            *INDEPENDENT_PERMISSION_DEFINITIONS.keys(),
        ],
    },
    "RECEIVING_OPERATOR": {
        "name": "Receiving Operator",
        "workflow_code": None,
        "permissions": [
            "receiving.read",
            "receiving.manage",
            "communications.read",
            "communications.send",
        ],
    },
    "RECEIVING_MANAGER": {
        "name": "Receiving Manager",
        "workflow_code": None,
        "permissions": [
            "receiving.read",
            "receiving.manage",
            "receiving.variances.manage",
            "receiving.backorders.manage",
            "communications.read",
            "communications.send",
        ],
    },
    "AP_CLERK": {
        "name": "Accounts Payable Clerk",
        "workflow_code": None,
        "permissions": [
            "invoices.read",
            "invoices.manage",
            "reconciliation.read",
            "communications.read",
            "communications.send",
        ],
    },
    "AP_APPROVER": {
        "name": "Accounts Payable Approver",
        "workflow_code": None,
        "permissions": [
            "invoices.read",
            "reconciliation.read",
            "reconciliation.manage",
            "communications.read",
            "communications.send",
        ],
    },
    "ANALYTICS_VIEWER": {
        "name": "Analytics Viewer",
        "workflow_code": None,
        "permissions": ["analytics.read", "communications.read", "communications.send"],
    },
    "ANALYTICS_MANAGER": {
        "name": "Analytics Manager",
        "workflow_code": None,
        "permissions": [
            "analytics.read",
            "analytics.reports.manage",
            "communications.read",
            "communications.send",
        ],
    },
    "FRANCHISE_OPERATOR": {
        "name": "Franchise Operator",
        "workflow_code": None,
        "permissions": [
            "events.read",
            "vendor_hall.read",
            "store_loadout.read",
            "store_loadout.store.checkin",
            "communications.read",
            "communications.send",
            "notifications.read",
        ],
    },
    "EVENT_STAFF": {
        "name": "Event Staff",
        "workflow_code": None,
        "permissions": [
            "events.read",
            "vendor_hall.read",
            "vendor_hall.staff.checkin",
            "store_loadout.read",
            "store_loadout.store.checkin",
            "communications.read",
            "communications.send",
            "notifications.read",
        ],
    },
    "VENDOR": {
        "name": "Vendor",
        "workflow_code": None,
        "permissions": [
            "vendor.portal",
            "vendor_hall.read",
            "vendor_hall.vendor.manage",
            "communications.read",
            "communications.send",
            "notifications.read",
        ],
    },
    "PURCHASING": {
        "name": "Purchasing",
        "workflow_code": None,
        "permissions": [
            "workflows.read",
            "orders.bpp.manage",
            "orders.independent.manage",
            "stores.manage",
            "stores.read",
            "configuration.manage",
            "receiving.read",
            "receiving.manage",
            "reconciliation.read",
            "purchase_orders.handoff",
            "analytics.read",
            "catalog.models.read",
            "communications.read",
            "communications.send",
            "notifications.read",
            "notifications.send",
            "vendor_hall.read",
            "vendor_hall.manage",
            "vendor_hall.staff.checkin",
            "vendor_hall.export",
            "vendor_hall.map.manage",
            "store_loadout.read",
            "store_loadout.manage",
            "store_loadout.store.checkin",
            "store_loadout.schedule.manage",
            "store_loadout.export",
            "event_settlement.read",
            "event_settlement.manage",
            "event_settlement.export",
            *BPP_PERMISSION_DEFINITIONS.keys(),
            *INDEPENDENT_PERMISSION_DEFINITIONS.keys(),
        ],
    },
    "RECONCILIATION": {
        "name": "Reconciliation",
        "workflow_code": None,
        "permissions": [
            "stores.read",
            "invoices.read",
            "invoices.manage",
            "reconciliation.read",
            "reconciliation.manage",
            "event_settlement.read",
            "event_settlement.manage",
            "event_settlement.export",
            "catalog.models.read",
            "communications.read",
            "communications.send",
            "notifications.read",
            "notifications.send",
        ],
    },
    "EXECUTIVE": {
        "name": "Executive",
        "workflow_code": None,
        "permissions": [
            "analytics.read",
            "snapshots.read",
            "communications.read",
            "communications.send",
            "notifications.read",
        ],
    },
    "ADMIN": {
        "name": "Administrator",
        "workflow_code": None,
        "permissions": list(CORE_PERMISSION_DEFINITIONS.keys()),
    },
}
